services:
  - type: web
    name: anipulse
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
      python manage.py seed_all
    startCommand: gunicorn config.wsgi --workers 2 --timeout 120
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      # ── Cloudinary (avatar/cover storage) ──
      - key: CLOUDINARY_CLOUD_NAME
        value: dlhv9d3jo
      - key: CLOUDINARY_API_KEY
        value: "329518554126186"
      - key: CLOUDINARY_API_SECRET
        value: EDQa0Id8gf5_Xm2Dm_8X7vxwHY8
