# Generated by Django 5.0.6 on 2026-05-05 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('anilist_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('site_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('is_general_spoiler', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anilist_id', models.IntegerField(db_index=True, unique=True)),
                ('title_romaji', models.CharField(max_length=500)),
                ('title_english', models.CharField(blank=True, max_length=500)),
                ('title_native', models.CharField(blank=True, max_length=500)),
                ('slug', models.SlugField(max_length=600, unique=True)),
                ('format', models.CharField(blank=True, choices=[('TV', 'TV'), ('TV_SHORT', 'TV Short'), ('MOVIE', 'Movie'), ('SPECIAL', 'Special'), ('OVA', 'OVA'), ('ONA', 'ONA'), ('MUSIC', 'Music')], max_length=20)),
                ('status', models.CharField(blank=True, choices=[('FINISHED', 'Finished'), ('RELEASING', 'Releasing'), ('NOT_YET_RELEASED', 'Not Yet Released'), ('CANCELLED', 'Cancelled'), ('HIATUS', 'Hiatus')], db_index=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('episodes', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, help_text='Per episode in minutes', null=True)),
                ('season', models.CharField(blank=True, choices=[('WINTER', 'Winter'), ('SPRING', 'Spring'), ('SUMMER', 'Summer'), ('FALL', 'Fall')], max_length=10)),
                ('season_year', models.IntegerField(blank=True, db_index=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('next_airing_episode', models.IntegerField(blank=True, null=True)),
                ('next_airing_at', models.DateTimeField(blank=True, null=True)),
                ('average_score', models.FloatField(blank=True, null=True)),
                ('mean_score', models.FloatField(blank=True, null=True)),
                ('popularity', models.IntegerField(blank=True, db_index=True, null=True)),
                ('trending', models.IntegerField(blank=True, db_index=True, null=True)),
                ('favourites', models.IntegerField(blank=True, null=True)),
                ('cover_image_large', models.URLField(blank=True, max_length=500)),
                ('cover_image_medium', models.URLField(blank=True, max_length=500)),
                ('cover_image_color', models.CharField(blank=True, max_length=10)),
                ('banner_image', models.URLField(blank=True, max_length=500)),
                ('is_adult', models.BooleanField(db_index=True, default=False)),
                ('site_url', models.URLField(blank=True)),
                ('trailer_site', models.CharField(blank=True, max_length=50)),
                ('trailer_id', models.CharField(blank=True, max_length=100)),
                ('trailer_thumbnail', models.URLField(blank=True, max_length=500)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('genres', models.ManyToManyField(blank=True, related_name='anime', to='anime.genre')),
                ('studios', models.ManyToManyField(blank=True, related_name='anime', to='anime.studio')),
            ],
            options={
                'ordering': ['-trending', '-popularity'],
            },
        ),
        migrations.CreateModel(
            name='AnimeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.anime')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.tag')),
            ],
            options={
                'ordering': ['-rank'],
                'unique_together': {('anime', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='anime',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='anime', through='anime.AnimeTag', to='anime.tag'),
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=500)),
                ('thumbnail', models.URLField(blank=True, max_length=500)),
                ('air_date', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_list', to='anime.anime')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('anime', 'number')},
            },
        ),
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=500)),
                ('icon', models.URLField(blank=True, max_length=500)),
                ('color', models.CharField(blank=True, max_length=10)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='anime.anime')),
            ],
            options={
                'ordering': ['site'],
                'unique_together': {('anime', 'site')},
            },
        ),
        migrations.AddIndex(
            model_name='anime',
            index=models.Index(fields=['status', 'season_year'], name='anime_anime_status_3944ba_idx'),
        ),
        migrations.AddIndex(
            model_name='anime',
            index=models.Index(fields=['format', 'status'], name='anime_anime_format_24e3f6_idx'),
        ),
        migrations.AddIndex(
            model_name='anime',
            index=models.Index(fields=['is_adult', 'trending'], name='anime_anime_is_adul_84e546_idx'),
        ),
    ]
