# Generated by Django 4.2.30 on 2026-05-09 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_battle_tierlist_useractivity_tierlistitem_streak_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_type', models.CharField(choices=[('OP', 'Opening'), ('ED', 'Ending')], max_length=3)),
                ('number', models.IntegerField(default=1)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('artist', models.CharField(blank=True, max_length=300)),
                ('video_url', models.URLField(blank=True, max_length=500)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='anime.anime')),
            ],
            options={
                'ordering': ['theme_type', 'number'],
            },
        ),
    ]
