# Generated by Django 4.2.30 on 2026-06-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0007_characterfavorite_stafffavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='anilist_review_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
