# Generated by Django 4.2.30 on 2026-06-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0010_migrate_socialpost_replies'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='is_daily_featured',
            field=models.BooleanField(default=False),
        ),
    ]
