# Generated by Django 4.2.30 on 2026-06-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0013_favoriteanime'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('FOLLOW', 'Follow'), ('LIKE', 'Like'), ('REVIEW', 'Review'), ('COMMENT', 'Comment'), ('TIER_LIST', 'Tier List'), ('BATTLE_VOTE', 'Battle Vote'), ('LEVEL_UP', 'Level Up'), ('BADGE', 'Badge'), ('SYSTEM', 'System')], default='SYSTEM', max_length=20),
        ),
    ]
