# Generated by Django 6.0.6 on 2026-06-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0014_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='post_type',
            field=models.CharField(choices=[('post', 'User Post'), ('discussion', 'Discussion'), ('episode_discussion', 'Episode Discussion'), ('trending', 'Trending Topic'), ('seasonal', 'Seasonal Discussion')], default='post', max_length=30),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='body',
            field=models.TextField(max_length=2000),
        ),
    ]
