# Generated by Django 6.0.6 on 2026-06-13 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0015_socialpost_post_type_socialpost_title_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='shared_ct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_posts', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='shared_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='body',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='post_type',
            field=models.CharField(choices=[('post', 'User Post'), ('discussion', 'Discussion'), ('episode_discussion', 'Episode Discussion'), ('trending', 'Trending Topic'), ('seasonal', 'Seasonal Discussion'), ('poll', 'Poll'), ('qotd', 'Question of the Day'), ('hot_take', 'Hot Take'), ('recommendation', 'Recommendation Thread'), ('share_battle', 'Shared Battle'), ('share_tierlist', 'Shared Tier List'), ('share_review', 'Shared Review')], default='post', max_length=30),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('WATCHING', 'Started Watching'), ('COMPLETED', 'Completed'), ('PLANNING', 'Plan to Watch'), ('REVIEW', 'Wrote a Review'), ('ACHIEVEMENT', 'Earned Achievement'), ('BATTLE', 'Voted in Battle'), ('POST', 'Made a Post'), ('STREAK', 'Reached Streak Milestone'), ('SHARE', 'Shared Content'), ('POLL_VOTE', 'Voted in a Poll')], max_length=20),
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('is_multiple', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='anime.socialpost')),
            ],
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='anime.poll')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='anime.socialpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'post')},
            },
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='anime.polloption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('option', 'user')},
            },
        ),
    ]
