# Generated by Django 6.0.6 on 2026-06-18 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0016_feed_evolution_polls_bookmarks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleArgument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.IntegerField(help_text='1 for anime1, 2 for anime2')),
                ('body', models.TextField(max_length=500)),
                ('votes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arguments', to='anime.battle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-votes', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BattleArgumentVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=1, help_text='1 for upvote, -1 for downvote')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('argument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_votes', to='anime.battleargument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('argument', 'user')},
            },
        ),
        migrations.CreateModel(
            name='BattleCategoryVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('story', 'Story'), ('characters', 'Characters'), ('animation', 'Animation'), ('villains', 'Villains'), ('world_building', 'World Building'), ('emotional_impact', 'Emotional Impact')], max_length=30)),
                ('choice', models.IntegerField(help_text='1 for anime1, 2 for anime2')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_votes', to='anime.battle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('battle', 'user', 'category')},
            },
        ),
    ]
