# Generated by Django 4.2.30 on 2026-06-06 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_watchlist_public',
            field=models.BooleanField(default=True),
        ),
    ]
